name: nested_menu_bar
description: "Nested Menu Bar is a horizontal menu ber for flutter. It is a simple and easy to use.It allows you to create a nested menu bar with ease."
version: 1.0.1
homepage: https://github.com/Rajkumarbhakta/nested_menu_bar
repository: https://github.com/Rajkumarbhakta/nested_menu_bar

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
